### PR TITLE
Mercury Updated

### PR DESCRIPTION
**Pull request by suirad**
Added a bit of code to update mercury functionality of JukeAlert.
Added a configurable option to enable/disable cross server snitch alerts.

### CODE REVIEW

**Comment by suirad** [comment]
@rourke750 @ttk2 @drjawa 
Good to merge, this probably needs a CLA

**Comment by rourke750** [comment]
You got the wrong import for chatcolor

@rourke750 <https://github.com/rourke750> @ttk2 <https://github.com/ttk2>
@drjawa <https://github.com/drjawa>
Good to merge, this probably needs a CLA

—
Reply to this email directly or view it on GitHub
<https://github.com/Civcraft/JukeAlert/pull/32#issuecomment-114597873>.

**Comment by suirad** [comment]
@rourke750 good catch, want me to submit another pull or not worry about it?

**Comment by jjj5311** [comment]
you should't need a new pull just fix it in your master and it will be added here as another commit

**Comment by rourke750** [comment]
@drjawa ...................

@suirad looks like you need to do a new pull

**Comment by suirad** [comment]
Ah okay, wasnt sure it would pick it up since its already merged. Actually if jawa/rourke wants to revert i can squash that new commit no problem

**Comment by drjawa** [comment]
Oh you said it was good to merge. Missed the chat color. I reverted.

**Comment by drjawa** [comment]
Though it seems once a pull is closed it doesn't reopen so a new pull might be needed away.

**Comment by rourke750** [comment]
Well the revert wasn't needed. It'll just complicate things.

**Comment by suirad** [comment]
Updated my commit, want me to make another pull?

**Comment by rourke750** [comment]
Yes pls

**Comment by suirad** [comment]
https://github.com/Civcraft/JukeAlert/pull/34

**Pull request merged**
