### PR TITLE
Fix for displaying of cart logs

### PR DESCRIPTION
**Pull request by Maxopoly**
Apparently missed that when I initially made the pull request and noone else remembered as well. Should be good to merge.

### CODE REVIEW

**Comment by Maxopoly** [comment]
@ttk2 @erocs  pls

**Comment by erocs** [comment]
Build failed.  http://build.civcraft.co/job/JukeAlert-master/204/console

@rourke750 Jenkins dependency issue.

**Comment by Maxopoly** [comment]
Ah, the link for our repo is outdated, http://civcraft.co:8080/plugin/repository/everything/ doesnt work since the server shuffling, it works for me with http://build.civcraft.co/plugin/repository/everything/

**Comment by erocs** [comment]
Rourke fixed it (Thanks Rourke!). @ttk2 If the vehicle tracking is live on main, go ahead and stage this for tomorrow. http://build.civcraft.co/job/JukeAlert-master/205/

**Comment by ttk2** [comment]
staged

**Pull request merged**
