### PR TITLE
Test, DO NOT MERGE

### PR DESCRIPTION
**Pull request by Maxopoly**
Making this as PR so I can easily make a test build in this dependency mess.

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
ok to test

**Comment by Maxopoly** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by Maxopoly** [comment]
This will probably fix the GroupInvalidationEvent snitch group thing, but the test build is broken so I cant test it. Should I just merge it, hope the build works there and fix it if needed or do you want to figure out what broke when trying to build this?

**Pull request closed without merging**
