### PR TITLE
Add timezone information to /jainfo

### LINKED ISSUE #18: Minor niggle about timezones.
Just a suggestion but could we please have the snitch reports print somewhere on them what timezone the timestamps are in please? Ideally (I don't know how easy it would be to do) it should be in the timezone of the player but failing that a label would be nice.

### PR DESCRIPTION
**Pull request by waffle-stomper**
Closes #18 

This adds an extra line to the /jainfo header. For example:

    Snitch Log for Wheat_Farm -----------------------------------
    All times are EDT (UTC-04:00)
     $59 = Wheat
     Name                Reason                Details

I'm not very familiar with git yet, so I'm not sure why there are four commits showing up here instead of just the one. I thought the merge would take care of that?

### CODE REVIEW

**Comment by Maxopoly** [comment]
Could you make the timezone configurable for others running the plugin?

**Comment by waffle-stomper** [comment]
I'm using the system timezone to generate that line, which I believe is what's used for [generating the times in the report](https://github.com/Civcraft/JukeAlert/blob/master/src/com/untamedears/JukeAlert/storage/JukeAlertLogger.java#L1257). It shouldn't need any manual configuring, should it?

**Comment by Maxopoly** [comment]
Oh yeah, nevermind, I read UTC in the diff and thought it was completly hardcoded. @ProgrammerDan any objections?

**Comment by ProgrammerDan** [comment]
Assuming tested, no objections. Perhaps toss on test first so we can test along with minecart location breaks.

@waffle-stomper Doublecheck the snitch log parsing in Snitch Visualizer, once this is merged and online one of us would probably have to add a change to the parse-logic :).

**Comment by waffle-stomper** [comment]
@ProgrammerDan Haha! If I'd realized I was making more work for myself, I would have chosen a different issue to fix! 

I've tested it locally and it seems to work as intended.

**Pull request merged**
