### PR TITLE
Add snitch names to jalist output

### LINKED ISSUE #24: Please put the snitch name in jalist's output.
It would help with working out where they are faster, without having to transfer the coordinates to a waypoint mod.

### PR DESCRIPTION
**Pull request by waffle-stomper**
Fixes #24 

I've tested it locally against Spigot 1.10.2 and it seems to work as intended. The columns are a little wonky, but I don't think that's fixable unless Minecraft reverts to a monospaced font.

- Added the snitch name column to output
- Removed the world name column from output
- Added the world name to the first line of the header
- Added an optional suffix argument to ChatFiller.fillString (instead of
just chopping off an arbitrary number of characters and adding the
suffix in JukeAlertLogger.getSnitchList)
- JukeAlertLogger.getSnitchList now returns an instance of
SendSnitchList. This was necessary to add the world name.
- Added hover text to each line so long snitch & group names can be displayed in full (and parsed by mods like Snitch-Visualizer)

### CODE REVIEW

**Comment by Maxopoly** [comment]
You should consider using rebase instead of local merge, so you don't have 5 merge commits in each PR. Assuming this is tested, it looks nice though.

**Comment by waffle-stomper** [comment]
Thanks for the tip! I'm still figuring out how to use git.

**Comment by erocs** [comment]
World names would matter for non-sharded servers.

**Comment by waffle-stomper** [comment]
That's a good point. 

I could probably add a config option that enables the world name column, (by reducing the width of the group and snitch name columns), and disables the world name in the header, (since it only displays the world name for the first snitch in the list). Would that work?

**Comment by waffle-stomper** [comment]
I've added the config option I mentioned. I've tested locally it and it seems to work as intended.

**Comment by Maxopoly** [comment]
Ok, nice. Good work

**Pull request merged**
