### PR TITLE
Teleporting now triggers snitches

### PR DESCRIPTION
**Pull request by TealNerd**
Previously teleporting into a snitch field (such as exiting a minecart and teleporting up because of humbug) did not trigger snitches. Now it will.

### CODE REVIEW

**Comment by ttk2** [comment]
good idea, does this just catch the teleport event?

**Comment by TealNerd** [comment]
Yeah, uses the same logic as the player move event basically just on teleport instead

**Comment by ttk2** [comment]
thoughts @rourke750 ?

**Comment by TealNerd** [comment]
@ttk2 this also has #49 in it as well if that's ok

**Comment by ttk2** [comment]
might not be, we just need to complete discussion on both before merging.

**Comment by TealNerd** [comment]
Ok I can always revert one or the other

**Comment by ProgrammerDan** [comment]
Alright, two thoughts.

1) definitely pull #49 into its own pull request

2) Can we just directly fire the existing movement code, instead of recreating it here? Now we just have a double-code liability where if we need to change movement listener we have to remember to change it here too. 

Otherwise, didn't even know this was an issue but great catch! Thanks for tackling :)

**Comment by TealNerd** [comment]
Yeah that's a good point, I fixed it.

**Comment by ProgrammerDan** [comment]
Awesome, looks good.

**Comment by rourke750** [comment]
@ProgrammerDan Want to handle this?

**Comment by TealNerd** [comment]
@rourke750  merge so i can do the block break thing?

**Comment by rourke750** [comment]
Any idea why all those lines got modified?

**Comment by TealNerd** [comment]
I think it was github getting confused about line numbers or something idk

**Pull request merged**
