### PR TITLE
Mute persist

### PR DESCRIPTION
**Pull request by jjj5311**
This is pretty ugly but it is working

Tested it and no more exceptions were coming up, this probably needs to be tested on a larger database then my 2 accounts lol

I can do the code cleanup once it has been tested and is working

### CODE REVIEW

**Comment by ttk2** [comment]
we would prefer the tested and working thing happen before it gets merged
into main, Wild was working on some way for us to get the build server to
make a .jar without putting it in main

**Comment by jjj5311** [comment]
Well I tested everything and it seems to work as desired.

Really there isnt much to clean up but the old ignore group stuff I just
commented out

**Comment by rourke750** [comment]
@jjj5311 So you think this is ready?

**Comment by jjj5311** [comment]
Yeah I think it works, I tested locally, but only 2 accounts... I think
it's good for civtest

**Comment by rourke750** [comment]
@ttk2 Civtest pls.

**Comment by ttk2** [comment]
done

**Pull request merged**
